version: '3'

services:

  bridge:
    image: douglara/chatwoot-botpress-bridge:1
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=Testing1234
      - BOTPRESS_ENDPOINT=http://botpress:3000
      - BOTPRESS_BOT_ID=hello
      - CHATWOOT_ENDPOINT=http://chatwoot:3000
      - CHATWOOT_BOT_TOKEN=password
    ports:
      - '3002:3000'

volumes:
  postgres:
  redis: